name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and push Docker image to Google Artifact Registry
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/scrap/main:latest .
          docker push asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/scrap/main:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy code-runner --image=asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/scrap/main:latest --platform=managed --region=asia-south1 --allow-unauthenticated
